In [1]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array


In [2]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
print(np.random.randint(5, size=2700))

[1 1 2 ... 2 0 3]


In [3]:
print(np.random.randint(5, size=[5,2]))

[[3 2]
 [1 4]
 [2 2]
 [3 0]
 [3 2]]


In [4]:
print(np.random.randint(2700, size=[5,2]))

[[ 198 1336]
 [1208  524]
 [2565  589]
 [ 234 1542]
 [ 434 1224]]


In [5]:
print(np.random.randint(2700, size=5))

[ 589  196 1870 1273 1844]


In [6]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = []
for i in clusters_amount:
    centroids_array.append(centroids_array, filtered_data[centroids_numbers[i]], axis=1)


TypeError: 'int' object is not iterable

In [7]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = []
while i in clusters_amount:
    centroids_array.append(centroids_array, filtered_data[centroids_numbers[i]], axis=1)


NameError: name 'i' is not defined

In [8]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = []
while i=0 in clusters_amount:
    centroids_array.append(centroids_array, filtered_data[centroids_numbers[i]], axis=1)


SyntaxError: invalid syntax (<ipython-input-8-eb0d6abca784>, line 19)

In [9]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = []
i = 0
while i <= clusters_amount:
    centroids_array.append(centroids_array, filtered_data[centroids_numbers[i]], axis=1)


TypeError: append() takes no keyword arguments

In [10]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = []
i = 0
while i < clusters_amount:
    centroids_array.append(centroids_array, filtered_data[centroids_numbers[i]], axis=1)


TypeError: append() takes no keyword arguments