In [1]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = np.empty([clusters_amount, 16634])#np.empty_like(filtered_data)
i = 0
while i < clusters_amount:
    randompatient = centroids_numbers[i]
    centroids_array = np.append(centroids_array, [filtered_data[randompatient, :]], axis = 0)
    i += 1

In [2]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = np.empty([clusters_amount, 16634])#np.empty_like(filtered_data)
i = 0
while i < clusters_amount:
    randompatient = centroids_numbers[i]
    centroids_array = np.append(centroids_array, [filtered_data[randompatient, :]], axis = 0)
    i += 1

print(centroids_array)

[[1.05499417e-311 1.05510433e-311 1.67982320e-322 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 3.68078906e-321
  3.68572972e-321 3.69067037e-321]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]]


In [3]:
# Import libraries
import numpy as np
import pandas 
import matplotlib.pyplot as pp
import matplotlib.cm as cm
import scanpy as sc

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = np.empty([0, 16634])
i = 0
while i < clusters_amount:
    randompatient = centroids_numbers[i]
    centroids_array = np.append(centroids_array, [filtered_data[randompatient, :]], axis = 0)
    i += 1

print(centroids_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]


In [4]:
max(centroids_array)


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [5]:
np.max(centroids_array)


110.0

In [6]:
# Import libraries
import numpy
import pandas
import matplotlib.pyplot as pyplot
import matplotlib.cm as cm
import scanpy as sc

def dist(patient_point, cluster_number):
    a = [filtered_data[patient_point, :]]
    b = [centroids_array[cluster_number, :]]
    dist = numpy.linalg.norm(a-b)

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = np.empty([0, 16634])
i = 0
while i < clusters_amount:
    randompatient = centroids_numbers[i]
    centroids_array = np.append(centroids_array, [filtered_data[randompatient, :]], axis = 0)
    i += 1

print(centroids_array)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
dist(201,2)


TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [8]:
# Import libraries
import numpy
import pandas
import matplotlib.pyplot as pyplot
import matplotlib.cm as cm
import scanpy as sc

def dist(patient_point, cluster_number):
    a = filtered_data[patient_point, :]
    b = centroids_array[cluster_number, :]
    dist = numpy.linalg.norm(a-b)

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = np.empty([0, 16634])
i = 0
while i < clusters_amount:
    randompatient = centroids_numbers[i]
    centroids_array = np.append(centroids_array, [filtered_data[randompatient, :]], axis = 0)
    i += 1

print(centroids_array)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
dist(201,3)


In [10]:
# Import libraries
import numpy
import pandas
import matplotlib.pyplot as pyplot
import matplotlib.cm as cm
import scanpy as sc

def dist(patient_point, cluster_number):
    a = filtered_data[patient_point, :]
    b = centroids_array[cluster_number, :]
    dist = numpy.linalg.norm(a-b)
    return dist

# Import data
data = sc.read_10x_mtx('./data/filtered_gene_bc_matrices/hg19/', var_names='gene_symbols', cache=True)

#Filter useless data
sc.pp.filter_genes(data, min_cells=1)
filtered_data = np.array(data._X.todense())

#Create Centroid Array
clusters_amount = 5
centroids_numbers = np.random.randint(2700, size=clusters_amount)
centroids_array = np.empty([0, 16634])
i = 0
while i < clusters_amount:
    randompatient = centroids_numbers[i]
    centroids_array = np.append(centroids_array, [filtered_data[randompatient, :]], axis = 0)
    i += 1

print(centroids_array)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [11]:
dist(291,2)


288.9221348391293